[package]
edition = "2018"
name = "show-notes"
# Version will match released show number! Episode 12 will be `0.1.2`.
version = "0.2.8"
authors = ["Chris Krycho <chris@chriskrycho.com>"]

[dependencies]
regex = "0.2"
